version: '3'

services:
  client:
    build: ./client
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - media:/usr/share/nginx/html/media
      - static:/usr/share/nginx/html/static

  server:
    build: ./server
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - static:/core/static
      - media:/core/media

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
  static:
  media:
