version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    build: ./server
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  client:
    build: ./client/proxy
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    env_file:
      - .env

volumes:
  db_data:
