# Generated by Django 4.2.2 on 2023-07-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
