# Generated by Django 4.2.2 on 2023-07-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
