# Generated by Django 4.2.2 on 2023-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_category_slug_remove_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
