# Generated by Django 4.2.2 on 2023-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
