# Generated by Django 4.2.2 on 2023-07-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
