name: CI/CD

on:
  push:
    branches:
      - devops

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io

      - name: Build and test
        run: |
          docker-compose build
          docker-compose up -d
          chmod +x ./tests/main.sh
          ./tests/main.sh

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker images
        run: |
          docker-compose push
          docker tag ecommerce:tag franciszekszeptycki/ecommerce:tag
          docker push franciszekszeptycki/ecommerce:tag

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: 64.226.82.152
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            docker-compose pull
            docker-compose up -d
